export const GET_BUCKET_LIST_REQUESTED = 'GET_BUCKET_LIST_REQUESTED';
export const GET_BUCKET_LIST_SUCCESS = 'GET_BUCKET_LIST_SUCCESS';
export const GET_BUCKET_LIST_FAILED = 'GET_BUCKET_LIST_FAILED';

export const ADD_NEW_BUCKET_REQUESTED = "ADD_NEW_BUCKET_REQUESTED";
export const ADD_NEW_BUCKET_SUCCESS = "ADD_NEW_BUCKET_SUCCESS";
export const ADD_NEW_BUCKET_FAILED = "ADD_NEW_BUCKET_FAILED";

export const GET_CARD_LIST_REQUESTED = "GET_CARD_LIST_REQUESTED";
export const GET_CARD_LIST_SUCCESS = "GET_CARD_LIST_SUCCESS";
export const GET_CARD_LIST_FAILED = "GET_CARD_LIST_FAILED";

export const ADD_NEW_CARD_REQUESTED = "ADD_NEW_CARD_REQUESTED";
export const ADD_NEW_CARD_SUCCESS = "ADD_NEW_CARD_SUCCESS";
export const ADD_NEW_CARD_FAILED = "ADD_NEW_CARD_FAILED";

export const DELETE_CARD_REQUESTED = "DELETE_CARD_REQUESTED";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAILED = "DELETE_CARD_FAILED";

export const UPDATE_CARD_REQUESTED = "UPDATE_CARD_REQUESTED";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const UPDATE_CARD_FAILED = "UPDATE_CARD_FAILED";

export const UPDATE_BUCKET_NAME_REQUESTED = 'UPDATE_BUCKET_NAME_REQUESTED';
export const UPDATE_BUCKET_NAME_SUCCESS = 'UPDATE_BUCKET_NAME_SUCCESS';
export const UPDATE_BUCKET_NAME_FAILED = 'UPDATE_BUCKET_NAME_FAILED';


export const SAVE_HISTORY_REQUESTED = 'SAVE_HISTORY_REQUESTED';
export const SAVE_HISTORY_SUCCESS = 'SAVE_HISTORY_SUCCESS';
export const SAVE_HISTORY_FAILED = 'SAVE_HISTORY_FAILED';

export const GET_HISTORY_LIST_REQUESTED = "GET_HISTORY_LIST_REQUESTED";
export const GET_HISTORY_LIST_SUCCESS = "GET_HISTORY_LIST_SUCCESS";
export const GET_HISTORY_LIST_FAILED = "GET_HISTORY_LIST_FAILED";